### ISSUE TITLE
Remove event and gallery from nav bar 

### ISSUE THREAD

**Issue by Surajbokde** [Surajbokde/Nature_Beauty#1]
remove event and gallery from nav bar ,from all pages.

**Comment by Harshith2255** [comment]
hello
I would like to contribute to this project

**Comment by Aavishkumar** [comment]
Hi , Can I try this ,I had joined the slack channel.

**Comment by Surajbokde** [comment]
@Aavishkumar thanks for showing interest i will assign this issue to u ,make PR on 7th dec
