### ISSUE TITLE
update contribution.md file

### ISSUE THREAD

**Issue by Surajbokde** [Surajbokde/Nature_Beauty#11]
update steps to contribute by adding screenshot .
there are git command you just wants to update command and add proper steps with screenshot ,from fork to make successfull pr.

**Comment by shilpachaudhury18** [comment]
HI @Surajbokde .I would like to contribute to this issue after 6th December. I have registered myself for Kwoc

**Comment by Surajbokde** [comment]
@shilpachaudhury18  introduce yourself in introduction channel .
 i will assign you this issue , but be ready with your code and upload screenshot in drive or anywhere on internet coz we have to add screenshot by using img- links.

**Comment by shilpachaudhury18** [comment]
Ok sure.

**Comment by shilpachaudhury18** [comment]
Just confirming that I need to provide the screenshot of the entire page. Right?

**Comment by Surajbokde** [comment]
entire page is not require .
![image](https://user-images.githubusercontent.com/66197682/101259816-340bcf80-3751-11eb-8396-46800d07eb9e.png)

just like this 
the above image show the link ,when u pull the code so make use of the given link

**Comment by shilpachaudhury18** [comment]
ok.Thanks
