### ISSUE TITLE
create cards of blog in blog.html

### ISSUE THREAD

**Issue by Surajbokde** [Surajbokde/Nature_Beauty#15]
![image](https://user-images.githubusercontent.com/66197682/101281015-b6000500-37f2-11eb-9981-898a244300b9.png)
something like this you ant to create in which date, comment,share , and author name will be there.

**Comment by shilpachaudhury18** [comment]
I want to work on this issue @Surajbokde

**Comment by Surajbokde** [comment]
@shilpachaudhury18 i  assign u this task "raise the fund for nature" ,"raise the fund for trees plantation" 
make use for such title.
and make sue of image which is suitable for title.
make total 6 cards

3-3(desktop view)
2-2-2(tab view)
1-1-1-1-1-1(mobile view)

**Comment by shilpachaudhury18** [comment]
ok sure.

**Comment by shilpachaudhury18** [comment]
I have one question- where shall I place the cards? Will it be below or above the title (telescope 101)?

**Comment by Surajbokde** [comment]
first delete all written stuff blog an all then we want blog gallery then blog cards after that write a blog section

**Comment by shilpachaudhury18** [comment]
Ok .Got it

**Comment by Surajbokde** [comment]
@shilpachaudhury18 what is the progress

**Comment by Ayush7614** [comment]
@Surajbokde brother i have to work on this would you assign me

**Comment by shilpachaudhury18** [comment]
I already sent you one draft. Please check it out. I have some problems. @Surajbokde
