### ISSUE TITLE
create write a blog section in blog.html

### ISSUE THREAD

**Issue by Surajbokde** [Surajbokde/Nature_Beauty#16]
![image](https://user-images.githubusercontent.com/66197682/101281149-81d91400-37f3-11eb-801e-6213f6eab2eb.png)

i want the same form and in blog tag there is drowdown having option (volunteer,nature ,happiness)

**Comment by Harshith2255** [comment]
Hi
I want to contribute on this one.

**Comment by Harshith2255** [comment]
but should i add functionality to the" post blog "button

**Comment by Surajbokde** [comment]
@Harshith2255  add hover to post blog button.
and add this at bottom of blog.html above footer

**Comment by Harshith2255** [comment]
Okay thanks i will try my best

**Comment by Harshith2255** [comment]
So this is a new web page

**Comment by TusharDasMe** [comment]
Can I work on this?

**Comment by Surajbokde** [comment]
@TusharDasMe  plz wait let me see Harshith2255  work first ,at that time find another issue.

**Comment by Harshith2255** [comment]
pull request has been made have a look
