### ISSUE TITLE
Fix the overflow

### ISSUE THREAD

**Issue by Surajbokde** [Surajbokde/Nature_Beauty#2]
![image](https://user-images.githubusercontent.com/66197682/100540956-bc2c3980-3266-11eb-9682-b721e16a1806.png)

**Comment by Harshith2255** [comment]
HI
can i try the job

**Comment by Surajbokde** [comment]
@Harshith2255 did you join slack channel??

**Comment by Harshith2255** [comment]
no sorry @Surajbokde what is it?

**Comment by Surajbokde** [comment]
Join my Slack workspace! 
https://join.slack.com/t/kwocproject/shared_invite/zt-jky5lovn-qJa1czV569F6fnAsltds7g
@Harshith2255 this channel is used to discuss about the project.
i will share some guidelines of contribution .
after that you will be assign this issue.

**Comment by Harshith2255** [comment]
yeah so i have to hide the overflow?

**Comment by Surajbokde** [comment]
no create a slider for that

**Comment by itish-agarwal** [comment]
Hi can I work on this issue?

**Comment by Surajbokde** [comment]
@itish-agarwal start your work ,and make PR.
