### ISSUE TITLE
add proper validation in contact form at contact.html

### ISSUE THREAD

**Issue by Surajbokde** [Surajbokde/Nature_Beauty#20]
![image](https://user-images.githubusercontent.com/66197682/101350124-74d02980-38b4-11eb-97a5-8ccf0459cb0f.png)
currently it is look like this.

remove that label msg just  simple validation is required
![image](https://user-images.githubusercontent.com/66197682/101351431-95997e80-38b6-11eb-8378-95a005eaefcd.png)
just like this

**Comment by Aavishkumar** [comment]
hi, assign this to me

**Comment by Shagufta08** [comment]
Hey! I would like to contribute to this issue.

**Comment by Surajbokde** [comment]
@Shagufta08 do it .
i am assigning this issue to u.

**Comment by Surajbokde** [comment]
@Shagufta08 do it fast

**Comment by charchit95** [comment]
@Surajbokde Can I do this?
