### ISSUE TITLE
modify donation.html

### ISSUE THREAD

**Issue by Surajbokde** [Surajbokde/Nature_Beauty#23]
![image](https://user-images.githubusercontent.com/66197682/101447849-09d23180-394c-11eb-96ed-778febf52154.png)
this is current donation.html page

requirement:
![image](https://user-images.githubusercontent.com/66197682/101447951-3dad5700-394c-11eb-858c-e9a91b5f584e.png)
this part must be in cards and remove that text and add some good text over there according to headings
cards must have shadow and hover.

![image](https://user-images.githubusercontent.com/66197682/101448196-a3014800-394c-11eb-8862-a464acd71e3c.png)
all the fields remain same ,but do placed all fields at proper position and add hover effect over there .

**Comment by KeertimaanNayak** [comment]
I would like to take this issue

**Comment by KeertimaanNayak** [comment]
Hey myself Keertimaan here, I would like to take up this issue

**Comment by Surajbokde** [comment]
@KeertimaanNayak i am assigning this issue to u .
read the description .
if ur facing difficulty then ask me on slack.

**Comment by KeertimaanNayak** [comment]
@Surajbokde Okay sure i would ask you over there .

**Comment by Raviruler** [comment]
@Surajbokde i like to work on this issue. Please assign me this.
