### ISSUE TITLE
Home Link always Active in Navbar

### ISSUE THREAD

**Issue by charchit95** [Surajbokde/Nature_Beauty#28]
The Home In Navbar is always active, if we click on any other link too.
For example, if I click About then too the Home link is Active.

![image](https://user-images.githubusercontent.com/47504288/101620948-24cf9f00-3a3b-11eb-9f77-482f7c41ab29.png)

**Comment by charchit95** [comment]
I would like to work on this issue.

**Comment by Surajbokde** [comment]
@charchit95  do it and remove features and gallery from nav bar

**Comment by charchit95** [comment]
Ok Thanks
