### ISSUE TITLE
Reduce the header(navbar) height

### ISSUE THREAD

**Issue by Surajbokde** [Surajbokde/Nature_Beauty#3]
![image](https://user-images.githubusercontent.com/66197682/100540994-f5fd4000-3266-11eb-98d1-85eef9e5f882.png)
reduce the height of header navbar

**Comment by charchit95** [comment]
Please assign this issue to me

**Comment by Surajbokde** [comment]
@charchit95  start your work I will assign You .make PR after 6th dec.

**Comment by charchit95** [comment]
Ok
Thanks

**Comment by charchit95** [comment]
Thanks

**Comment by Surajbokde** [comment]
@charchit95 do it by today itself.

**Comment by Ayush7614** [comment]
@Surajbokde bro plss assign me this issue

**Comment by Surajbokde** [comment]
@Ayush7614 do it and make PR by today itself

**Comment by Surajbokde** [comment]
@charchit95 i am unassigning u

**Comment by Ayush7614** [comment]
Okk i will do from my side bro

**Comment by Ayush7614** [comment]
@Surajbokde bro i have to work on this or not

**Comment by Surajbokde** [comment]
@Ayush7614 sory to inform you late but this is solved

**Comment by Ayush7614** [comment]
@Surajbokde no problem brother
