### ISSUE TITLE
modify footer

### ISSUE THREAD

**Issue by Surajbokde** [Surajbokde/Nature_Beauty#33]

**Comment by itish-agarwal** [comment]
Hi I would like to know what exactly is to be done with the footer

**Comment by Surajbokde** [comment]
@itish-agarwal do following changes-
1> instead of about agency  add logo and below that write something about nature beauty.
2> in navigation links add only (home,about,donation,blog,contact)
3>  remove news latter and instafeed and add contact us in which mention address(of delhi) and below add icon of facebook ,twitter ,instagram ,linkedin.

currently there are 4 cols ,we wants 3 cols in ratio 2:1:1

**Comment by arbazkhan56** [comment]
Hi!
Can you assign me?

**Comment by omkar342** [comment]
Hi! I have completed first task and also created pull request..plz review and suggest changes if any....

**Comment by Rajdeep-G** [comment]
@Surajbokde  is this issue still open ? Can this be assigned to me ?

**Comment by shilpachaudhury18** [comment]
Hi. Is this issue still open? Then I want to do this work. @Surajbokde

**Comment by Surajbokde** [comment]
@itish-agarwal plz do it by today

**Comment by itish-agarwal** [comment]
Due to some emergency i am not able to work on it
My apologies

**Comment by Surajbokde** [comment]
@itish-agarwal r u going to do it by today or tomorrow
Or will i assign to someone else

**Comment by itish-agarwal** [comment]
Pls assign someone else as i am involved in some emergency

**Comment by abhishekjnvk** [comment]
I will work on it

**Comment by ghost** [comment]
i will work on it
