### ISSUE TITLE
content writing

### ISSUE THREAD

**Issue by Surajbokde** [Surajbokde/Nature_Beauty#34]
convert dummy text to meaningful text (related to our website)

**Comment by Raviruler** [comment]
Assign to me.

**Comment by Raviruler** [comment]
[https://docs.google.com/document/d/1GAjBeJu9fqXmsn8JyoECuoCAAzaufTyDUBHABbBocGc/edit#heading=h.wybsmuapexl6](url)

**Comment by Raviruler** [comment]
https://docs.google.com/document/d/1GAjBeJu9fqXmsn8JyoECuoCAAzaufTyDUBHABbBocGc/edit?usp=sharing

**Comment by Raviruler** [comment]
[Google Doc file of updated Index.html](https://docs.google.com/document/d/1a92hnur563fESeygRk-WWl9YOjk0bPL22Fa2dFwIYBg/edit?usp=sharing)

**Comment by Raviruler** [comment]
Completed my work.
@Surajbokde  please Close this Issue.
