### ISSUE TITLE
modify become a Volunteer form

### ISSUE THREAD

**Issue by Surajbokde** [Surajbokde/Nature_Beauty#35]
![image](https://user-images.githubusercontent.com/66197682/101981970-96eff000-3c96-11eb-94da-07c63952b927.png)
instead of that select i want field of mobile no.
add validation in all fields

**Comment by Harshith2255** [comment]
Hi
I would like to work on this

**Comment by Harshith2255** [comment]
But is style added through css or bootstrap

**Comment by the-halfbloodprince** [comment]
I too would like to work on this...

**Comment by Surajbokde** [comment]
@the-halfbloodprince  @Harshith2255  both of you work on this issue and send me ss .
i will confirm and then allow you to make pr.

**Comment by the-halfbloodprince** [comment]
Cool

**Comment by the-halfbloodprince** [comment]
![image](https://user-images.githubusercontent.com/55590289/101992729-52d30e80-3cdb-11eb-8c17-744f0b72d15a.png)

Added the phone number input... Does this look fine or any suggestions?

**Comment by Surajbokde** [comment]
@the-halfbloodprince it is ok,add validation also
