### ISSUE TITLE
modify blog page

### ISSUE THREAD

**Issue by Surajbokde** [Surajbokde/Nature_Beauty#41]
there is space in left and right of the page remove that 
![image](https://user-images.githubusercontent.com/66197682/102073727-ba976f80-3e29-11eb-95d3-30739dd438f2.png)
remove extra spacing in blog cards
![image](https://user-images.githubusercontent.com/66197682/102073841-e74b8700-3e29-11eb-98ee-8f60f57d22f3.png)

**Comment by Surajbokde** [comment]
@shilpachaudhury18 do u want to work

**Comment by KeertimaanNayak** [comment]
I want to take up this issue.

**Comment by Surajbokde** [comment]
@KeertimaanNayak go ahead,do it fast
and give heading "Donate" in Donatation.html ->form

**Comment by Rajdeep-G** [comment]
@Surajbokde is this issue still open ? Can this be assigned to me ?

**Comment by shilpachaudhury18** [comment]
I want to do this work. Can you please assign me? @Surajbokde
