### ISSUE TITLE
Make the home page more dynamic!

### ISSUE THREAD

**Issue by Pranav016** [Surajbokde/Nature_Beauty#47]
I would like to add some dynamic features and animations to the frontend and make the Home page more interactive.

I would like to work on this under **KWoC**

**Comment by Surajbokde** [comment]
@Pranav016 do it

**Comment by ineffable23** [comment]
I would like to work on this issue if it's still available

**Comment by Pranav016** [comment]
> I would like to work on this issue if it's still available

Sure go ahead. There was some issue with my environment so you can work on this.

**Comment by ineffable23** [comment]
Thanks @Pranav016 🙂

**Comment by ineffable23** [comment]
@Surajbokde please assign this issue to me

**Comment by Surajbokde** [comment]
@ineffable23  do it .

**Comment by Surajbokde** [comment]
@ineffable23 do add typewriter effect in heading of banner images .
make use some effects in every  pages .

**Comment by ineffable23** [comment]
Sure

**Comment by Surajbokde** [comment]
@ineffable23  first pull the changes i make the start working

**Comment by Surajbokde** [comment]
@ineffable23  do it fast

**Comment by ineffable23** [comment]
Yup I'm working on it

**Comment by Surajbokde** [comment]
@ineffable23  when u r making pr
