### ISSUE TITLE
works on php 

### ISSUE THREAD

**Issue by Surajbokde** [Surajbokde/Nature_Beauty#49]
make a folder "server"
add all html files in that folder
convert html to php files.
create database "nature_beauty" in that create table connect tables with the forms using php.

**Comment by shilpachaudhury18** [comment]
I would like to do this work. Can you please assign me? @Surajbokde

**Comment by Surajbokde** [comment]
@shilpachaudhury18 go ahead

**Comment by Surajbokde** [comment]
@shilpachaudhury18  any progress
