### ISSUE TITLE
update blog page by adding blog gallery

### ISSUE THREAD

**Issue by Surajbokde** [Surajbokde/Nature_Beauty#5]
gallery section and blog cards are require

**Comment by rutuja2229** [comment]
**I will like to work on this issue, will you please elaborate on this issue?**

**Comment by Surajbokde** [comment]
@rutuja2229  just like event gallery(at index.html) we want blog gallery at blog.html
and add img at banner area and change the heading to blogs
![image](https://user-images.githubusercontent.com/66197682/101278377-e5a61180-37e0-11eb-8a74-fc6eb9d4c519.png)

**Comment by ineffable23** [comment]
@Surajbokde I'm interested to work on this issue, please assign it to me.

**Comment by Surajbokde** [comment]
@rutuja2229 pull all the changes then make banner and gallery section in blog.html

**Comment by rutuja2229** [comment]
Okay
