### ISSUE TITLE
update contact page

### ISSUE THREAD

**Issue by Surajbokde** [Surajbokde/Nature_Beauty#6]
map, contact us form , address section needed

**Comment by mousoom** [comment]
hi @Surajbokde , i would like to work on this issue

**Comment by Aavishkumar** [comment]
hi @Surajbokde , I had joined the slack channel, Can I try this?

**Comment by Surajbokde** [comment]
@mousoom did u join slack workspace ??

**Comment by mousoom** [comment]
@Surajbokde yes i did

**Comment by Surajbokde** [comment]
@mousoom  introduce youself on slack and i will assign this issue to u. if you are facing difficulties then plz message me .

**Comment by mousoom** [comment]
Okay sure
