### ISSUE TITLE
update donation page and donate now on nav bar

### ISSUE THREAD

**Issue by Surajbokde** [Surajbokde/Nature_Beauty#7]

**Comment by shilpachaudhury18** [comment]
Can you please explain the issue?

**Comment by Surajbokde** [comment]
@shilpachaudhury18  thanks for showing interest .
just modify and design donation.html and change the form having following fields

1. name of doner
2. donation amount
3. mobile number.
4. address.
5. state
6.pincode
7city
8. state.
9.email
then add donation in nav bar and connect that with donation.html

**Comment by umar07** [comment]
I would like to do this, can you assign it?

**Comment by Surajbokde** [comment]
@umar07 start working on the issue i assigned u

**Comment by itish-agarwal** [comment]
Hi can I also work on this issue?

**Comment by Surajbokde** [comment]
@itish-agarwal  i assigned this issue to umar07 wait 2-3 days i will create new issues soon
