### ISSUE TITLE
create about us page

### ISSUE THREAD

**Issue by Surajbokde** [Surajbokde/Nature_Beauty#8]

**Comment by LazyCoder-1506** [comment]
Hi I would like to work on this. I have joined the slack channel. Please elaborate on what you need.

**Comment by Surajbokde** [comment]
@LazyCoder-1506 thanks for showing your interest.
you have to create about us page having navbar,header, header banner img, footer.

![image](https://user-images.githubusercontent.com/66197682/101234824-d17ee900-36e8-11eb-8b0d-050f8c1fb2a3.png)
add this from index.html

and then section of our mission.

you can take help of index .html just add "our mission" section .
make our mission by using container use bootstrap for that.

**Comment by Surajbokde** [comment]
i assigned you this issue Make PR after 7th dec.

**Comment by LazyCoder-1506** [comment]
Thanks.

**Comment by TusharDasMe** [comment]
Is this issue is solved? Or I can help?

**Comment by Surajbokde** [comment]
@TusharDasMe thanks for showing interest .i will create more issue just wait 2-3 more days u will also get chance to contribute.

**Comment by LazyCoder-1506** [comment]
i have made a PR. please review
