### ISSUE TITLE
add hover effect 

### ISSUE THREAD

**Issue by Surajbokde** [Surajbokde/Nature_Beauty#9]
![image](https://user-images.githubusercontent.com/66197682/100832680-57ebbe80-348e-11eb-9325-c0bfcde4da0b.png)
this is on index.html

**Comment by Paolo-Cosentino** [comment]
Hi, may I work on this? Is there anything specific you're after?

**Comment by Surajbokde** [comment]
@Paolo-Cosentino thanks for showing interest in this project. but this project will under KWOC  https://kwoc.kossiitkgp.org/  .
so for 1 month i will not accept PR of other than KWOC student.
if u want to participate in KWOC as student then you are welcome to work on any issue, otherwise wait for a month.

**Comment by rsriramc** [comment]
Hi. I would like to take up on this. Are any specific transitions expected?

**Comment by Surajbokde** [comment]
@ravisrc you have to wait till 6th dec. if @Paolo-Cosentino will not register on KWOC then i will assign it to you

**Comment by iamkrati22** [comment]
@ravisrc I would like to work on this issue. :)

**Comment by ravisrc** [comment]
> @ravisrc I would like to work on this issue. :)

Yeah. Ok you take up on that.

**Comment by Surajbokde** [comment]
@ravisrc start working on this issue .

**Comment by Surajbokde** [comment]
@iamkrati22 please search another issue .

**Comment by rsriramc** [comment]
Are any specific transitions expected or can we try ourselves that matches the theme and color scheme?

**Comment by ineffable23** [comment]
I'm interested to work on this issue
